name: flutter_application_1
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version du projet
version: 1.0.0+1

# Environnement SDK Dart
environment:
  sdk: ">=2.17.0 <3.0.0"

# Dépendances du projet
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/IslandMoments-Regular.ttf

  fonts:
    - family: Island Moments
      fonts:
        - asset: assets/fonts/IslandMoments-Regular.ttf
